cache: bundler
language: ruby
rvm:
  - "2.3.0"
  - "2.4.0"
  - "2.5.0"
  - "2.6.0"
  # Honestly, I don't know what I am doing, JRuby breaks on Travis different way each time...
  - jruby-9.2.5.0
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
  - bundle exec rubocop
